### ISSUE TITLE
První úkol - Rozvážka pizzy

### ISSUE THREAD

**Issue by VendulaDvorackova** [VendulaDvorackova/kurz-python-czechitas-2024#1]
Ahoj Pájo, 
přidala jsem do repozitáře soubor s úkolem. Je to tak v pořádku? 
Pokud něco nefunguje nebo je potřeba něco přepsat, dej vědět! 
Díky :-)

**Comment by srpwnd** [comment]
Ahoj Vendy! Vypadá to velmi dobře 😊 Cením použití `dataclass` 💪 

Doplním pár poznámek:

---

```python
    def add_extra(self, ingredient, quantity, price_per_ingredient):
        self.ingredients[ingredient] = quantity
        self.price += quantity * price_per_ingredient
        return
```

Zde je zbytečné na konci funkce psát `return`, když nevracíš žádnou hodnotu. 

`return` bez vrácené hodnoty používáme pouze pokud chceme funkci ukončit dřív než dojde k vyhodnocení celého zbytku kódu. Říká se tomu tzn `early return`, i tak je to ale docela kontrovezní téma z hlediska toho, jestli je to vhodná přístup.

---

```python
    def mark_delivered(self):
        if self.status != "Doručeno":
            self.status = "Doručeno"
            return 
```

Zde máš opět ten `return` na konci.

---

```python
    def assign_order(self, order: Order):
        if self.available == True:
            self.current_order = order
            self.available = "Na cestě"
            print(f"Uživateli {self.name} byla přiřazena objednávka: {order}")
            return
        else:
            return "Doručovatel je nedostupný."
```

Tady se nám taky zatoulal `return` navíc 😄 

Zároveň tady nechtěně přepisuješ proměnnou `available`, kterou jsi výše definovala jako `bool` na stringovou hodnotu `"Na cestě"`. Myslím, že jsi spíš chtěla aktualizovat stav dané objednávky? 😊 

---

```python
    def complete_delivery(self):
        self.current_order.mark_delivered()
        self.available = True
        return "Objednávka byla doručena."
```

Zde by se ještě hodilo vyčistit referenci na doručenou objednávku, aby nebyla nadále spojena s doručovatelem.

---

Celkově velmi super práce :tada:, tak si prosím jen uprav tyto drobnosti a můžeme to uzavřít 😊 

Kdybych něco nejasně vysvětlil, tak se ozvi a já doplním

**Comment by VendulaDvorackova** [comment]
Ahoj Pájo, děkuju za zpětnou vazbu. 😊 Vysvětlil jsi vše jasně. Pokusila jsem se kód upravit podle tvých poznámek, tak snad už je to ok. Kdyby ne, ozvi se a já na to ještě kouknu. Ještě jednou děkuju a přeju pěkný zbytek víkendu. Vidíme se zítra! 😊

**Comment by srpwnd** [comment]
U aktualizace statusu objednávky jsem to myslel tak, že by se měl aktualizovat status té přiřazené instance objednávky, tedy

```python
self.current_order.status = ...
```

A samozřejmě ta proměnná `available` by se měla přepínat podle toho, jestli má kurýr přiřazenou nějakou aktivní objednávku nebo ne. Takto jí nikde nepřepínáš, takže doručovatel je vždy dostupný a můžeš přemazat stávající doručovanou objednávku novou, pokud znovu zavoláš `assign_order()`

**Comment by VendulaDvorackova** [comment]
Ahojky, děkuju za trpělivost. 🙏 A prosím, koukni na to ještě jednou, zda už je vše v pořádku. Snad jo. 😅

**Comment by srpwnd** [comment]
Super, takto to vypadá v pořádku! Děkuji za spolupráci 💪 👩‍💻
