### ISSUE TITLE
Úkol 2

### ISSUE THREAD

**Issue by VendulaDvorackova** [VendulaDvorackova/kurz-python-czechitas-2024#2]
Ahojky Pájo, dávám, vědět, že jsem sem nahrála úkol 2. 
Až budeš mít čas, koukneš se na to, prosím? 
Děkuju moc! 
Vendula

**Comment by VendulaDvorackova** [comment]
Dobré ráno, připomínám se s úkolem. Mrkneš na to, prosím? Díky! 😊

**Comment by srpwnd** [comment]
Ahoj Vendy,

nemám tomu co vytknout, je to velmi hezky zpracované! 💪 

Označuji úkol za splněný 😊
